class_name LocalizationService
extends RefCounted

const DEFAULT_LANGUAGE := "zh_cn"
const LANGUAGE_NAMES := {
	"zh_cn": "简体中文",
	"ja_jp": "日本語",
	"en_us": "English",
}

const TYPE_NAMES := {
	"zh_cn": {
		"fire": "火",
		"water": "水",
		"electric": "电",
		"grass": "草",
		"rock": "岩",
		"wind": "风",
		"mist": "雾",
		"psychic": "念",
		"metal": "钢",
		"shadow": "影",
		"light": "光",
		"blaze": "焰",
		"grove": "林",
		"tide": "潮",
		"spark": "霆",
		"stone": "岩",
	},
	"ja_jp": {
		"fire": "炎",
		"water": "水",
		"electric": "雷",
		"grass": "草",
		"rock": "岩",
		"wind": "風",
		"mist": "霧",
		"psychic": "念",
		"metal": "鋼",
		"shadow": "影",
		"light": "光",
		"blaze": "焔",
		"grove": "森",
		"tide": "潮",
		"spark": "霆",
		"stone": "岩",
	},
	"en_us": {
		"fire": "Fire",
		"water": "Water",
		"electric": "Electric",
		"grass": "Grass",
		"rock": "Rock",
		"wind": "Wind",
		"mist": "Mist",
		"psychic": "Psychic",
		"metal": "Metal",
		"shadow": "Shadow",
		"light": "Light",
		"blaze": "Blaze",
		"grove": "Grove",
		"tide": "Tide",
		"spark": "Spark",
		"stone": "Stone",
	},
}

const STATUS_NAMES := {
	"zh_cn": {
		"slow": "减速",
		"weaken": "削弱",
		"vulnerable": "破绽",
		"haste": "加速",
		"guard": "防御",
	},
	"ja_jp": {
		"slow": "減速",
		"weaken": "弱体",
		"vulnerable": "隙",
		"haste": "加速",
		"guard": "防御",
	},
	"en_us": {
		"slow": "Slow",
		"weaken": "Weaken",
		"vulnerable": "Expose",
		"haste": "Haste",
		"guard": "Guard",
	},
}

const EFFECT_NAMES := {
	"zh_cn": {
		"heal": "治疗",
		"damage_all": "群体伤害",
		"slow": "减速",
		"weaken": "削弱",
		"vulnerable": "破绽",
		"haste": "加速",
		"guard": "防御",
	},
	"ja_jp": {
		"heal": "回復",
		"damage_all": "全体ダメージ",
		"slow": "減速",
		"weaken": "弱体",
		"vulnerable": "隙",
		"haste": "加速",
		"guard": "防御",
	},
	"en_us": {
		"heal": "Heal",
		"damage_all": "AoE Damage",
		"slow": "Slow",
		"weaken": "Weaken",
		"vulnerable": "Expose",
		"haste": "Haste",
		"guard": "Guard",
	},
}

const TARGET_NAMES := {
	"zh_cn": {
		"enemy": "敌方单体",
		"enemy_all": "敌方全体",
		"ally": "友方单体",
		"self": "自身",
	},
	"ja_jp": {
		"enemy": "敵単体",
		"enemy_all": "敵全体",
		"ally": "味方単体",
		"self": "自身",
	},
	"en_us": {
		"enemy": "Single Enemy",
		"enemy_all": "All Enemies",
		"ally": "Single Ally",
		"self": "Self",
	},
}

const SKILL_NAMES := {
	"zh_cn": {
		"ember_claw": "炽爪",
		"scorch_dive": "灼袭",
		"vine_whip": "缠藤",
		"harvest_hymn": "丰收曲",
		"tide_burst": "潮涌",
		"tidal_guard": "潮壳",
		"static_jolt": "静电击",
		"rush_echo": "疾返",
		"stone_ram": "裂岩角",
		"bulwark": "岩壁",
		"mist_dart": "雾羽",
		"hush_wing": "寂翼",
		"boss_shard": "裂辉束",
		"boss_pulse": "塔心脉冲",
	},
	"ja_jp": {
		"ember_claw": "炎爪",
		"scorch_dive": "灼襲",
		"vine_whip": "絡み蔦",
		"harvest_hymn": "収穫歌",
		"tide_burst": "潮撃",
		"tidal_guard": "潮殻",
		"static_jolt": "静電撃",
		"rush_echo": "疾返",
		"stone_ram": "裂岩角",
		"bulwark": "岩壁",
		"mist_dart": "霧羽",
		"hush_wing": "寂翼",
		"boss_shard": "裂輝束",
		"boss_pulse": "塔心パルス",
	},
	"en_us": {
		"ember_claw": "Ember Claw",
		"scorch_dive": "Scorch Dive",
		"vine_whip": "Vine Whip",
		"harvest_hymn": "Harvest Hymn",
		"tide_burst": "Tide Burst",
		"tidal_guard": "Tidal Guard",
		"static_jolt": "Static Jolt",
		"rush_echo": "Rush Echo",
		"stone_ram": "Stone Ram",
		"bulwark": "Bulwark",
		"mist_dart": "Mist Dart",
		"hush_wing": "Hush Wing",
		"boss_shard": "Radiant Shard",
		"boss_pulse": "Core Pulse",
	},
}

const TEXT := {
	"zh_cn": {
		"menu.title": "雾野远征",
		"menu.subtitle.runtime": "主界面 / 运行中远征",
		"menu.subtitle.start": "开始界面 / 新游戏 · 读取存档 · 设置",
		"menu.continue.season_end": "查看年度结算",
		"menu.continue.run": "继续当前远征",
		"menu.start_game": "开始游戏",
		"menu.new_run": "开始新远征",
		"menu.load_save": "读取存档",
		"menu.settings": "设置",
		"menu.hint.runtime": "[b]主界面[/b]\n继续当前远征，或直接重开新的一局。最近一次 [b]日初存档[/b] 会保留给读取入口。",
		"menu.hint.start": "[b]开始界面[/b]\n开始游戏会创建一局新远征；读取存档会回到最近一次 [b]日初存档[/b]。",
		"menu.save.none": "[b]日初存档[/b]\n当前没有可读取的运行存档。",
		"menu.save.old": "[b]日初存档[/b]\n检测到旧存档，但摘要信息缺失。",
		"menu.save.latest": "[b]最近一次日初存档[/b]",
		"menu.summary.position": "当前位置：{node}",
		"menu.summary.battle_slots": "双打位：{value}",
		"menu.summary.weekly_objective": "周目标：{value}",
		"menu.summary.unassigned": "未配置",
		"menu.summary.no_objective": "暂无目标记录",
		"menu.summary.camp": "营地",
		"settings.summary.title": "[b]当前设置[/b]",
		"settings.summary.window": "窗口模式：{value}",
		"settings.summary.resolution": "窗口分辨率：{value}",
		"settings.summary.motion": "动效强度：{value}",
		"settings.summary.tutorials": "教学提示：{value}",
		"settings.summary.language": "语言：{value}",
		"settings.title": "设置",
		"settings.body": "在开始界面直接调整窗口模式、窗口分辨率、动效强度、教学提示和语言。",
		"settings.back": "返回开始界面",
		"settings.window.to_windowed": "切换到窗口",
		"settings.window.to_fullscreen": "切换到全屏",
		"settings.resolution.set": "设为 {value}",
		"settings.motion.to_standard": "切到标准动效",
		"settings.motion.to_reduced": "切到精简动效",
		"settings.tutorials.enable": "开启教学提示",
		"settings.tutorials.disable": "关闭教学提示",
		"settings.current": "当前：{value}",
		"settings.window.fullscreen": "全屏",
		"settings.window.windowed": "窗口",
		"settings.motion.standard": "标准",
		"settings.motion.reduced": "精简",
		"settings.tutorials.on": "开启",
		"settings.tutorials.off": "跳过",
		"settings.language.zh_cn": "切换到简体中文",
		"settings.language.ja_jp": "切换到日语",
		"settings.language.en_us": "切换到英语",
		"battle.default_title": "遭遇战",
		"battle.start": "战斗开始",
		"battle.end": "战斗结束",
		"battle.end.win": "胜利",
		"battle.end.lose": "败退",
		"battle.round": "第 {round} 轮",
		"battle.round_actor": "第 {round} 轮 · {actor}",
		"battle.turn.player": "我方回合",
		"battle.turn.enemy": "敌方行动",
		"battle.roster.allies": "我方单位",
		"battle.roster.enemies": "敌方单位",
		"battle.prompt.player": "轮到 {actor} 行动。先选技能，再点击目标确认。",
		"battle.prompt.choose_target": "{actor} 准备使用 {skill}。点击合法目标确认行动。",
		"battle.prompt.choose_enemy_column": "请点击右侧敌方单位列表中的目标。",
		"battle.prompt.choose_ally_column": "请点击左侧我方单位列表中的目标。",
		"battle.prompt.enemy_target": "敌方目标：{target}",
		"battle.prompt.ally_target": "友方目标：{target}",
		"battle.prompt.none": "未选目标",
		"battle.prompt.target": "当前锁定：{target}",
		"battle.prompt.target_none": "当前锁定：未选目标",
		"battle.prompt.enemy_thinking": "{actor} 正在评估局势…",
		"battle.prompt.enemy_intent": "{actor} 锁定 {target}，准备使用 {skill}。",
		"battle.prompt.action_locked": "{actor} 锁定 {target}，即将使用 {skill}。",
		"battle.prompt.capture_locked": "{actor} 锁定 {target}，准备尝试捕缚。",
		"battle.capture": "尝试捕缚",
		"battle.capture_hint": "对低生命野怪成功率更高",
		"battle.capture_success_title": "捕缚成功",
		"battle.preview.idle": "等待行动预览",
		"battle.preview.idle_detail": "选择技能后，这里会显示行动者、目标和预计影响。",
		"battle.preview.await_actor": "{actor} 待命中",
		"battle.preview.await_detail": "先选择技能，再点击目标确认。",
		"battle.preview.estimate_damage": "预计伤害 {min}-{max}",
		"battle.preview.estimate_heal": "预计治疗 {value}",
		"battle.preview.guard": "获得防御姿态",
		"battle.preview.status_apply": "附加 {status}",
		"battle.preview.enemy_all_damage": "范围伤害 {value}",
		"battle.preview.click_target": "点击高亮目标确认",
		"battle.preview.cancel": "取消当前预览",
		"battle.turn_order.now": "当前行动",
		"battle.turn_order.next": "下一个",
		"battle.turn_order.done": "已行动",
		"battle.turn_order.ready": "待命",
		"battle.card.acting": "行动中",
		"battle.card.targeted": "锁定中",
		"battle.card.selected": "已选中",
		"battle.card.confirm": "可确认",
		"battle.card.hit": "受击",
		"battle.card.ko": "KO",
		"battle.marker.active": "[行动]",
		"battle.marker.enemy_target": "[敌方目标]",
		"battle.marker.ally_target": "[友方目标]",
		"battle.stat.attack": "攻击",
		"battle.stat.speed": "速度",
		"battle.stat.hp": "生命",
		"battle.skill.power": "威力 {value}",
		"battle.skill.effect": "效果 {value}",
		"battle.skill.target": "目标 {value}",
		"battle.log.enemy_all": "{actor} 释放 {skill}，压制了全体敌人。",
		"battle.log.no_target": "{actor} 的 {skill} 没有合法目标。",
		"battle.log.heal": "{actor} 对 {target} 使用 {skill}，回复 {value} 点生命。",
		"battle.log.guard": "{actor} 通过 {skill} 进入防御姿态。",
		"battle.log.damage": "{actor} 对 {target} 使用 {skill}，造成 {value} 点伤害。{target} 生命 {hp}/{max_hp}{suffix}",
		"battle.log.status": "{target} 获得状态：{status}。",
		"battle.log.capture_success": "{actor} 成功捕缚了 {target}。",
		"battle.log.capture_fail": "{actor} 的捕缚失败了，{target} 仍在挣扎。",
		"battle.log.round_limit": "达到 {value} 回合上限，按场上剩余战力结算。",
		"battle.log.bonus.attack": "羁绊增益：我方攻击 +{value}。",
		"battle.log.bonus.speed": "羁绊增益：我方速度 +{value}。",
		"battle.log.bonus.hp": "羁绊增益：我方体力 +{value}。",
		"battle.log.bonus.heal": "羁绊增益：治疗效果 +{value}。",
		"battle.log.bonus.guard": "建筑增益：开场减伤 {value}%。",
		"battle.log.bonus.enemy_penalty": "压制生效：敌方攻击 -{value}。",
		"battle.suffix.super": " · 克制",
		"battle.suffix.resist": " · 被抗",
		"battle.subtitle.slots": "双打位：{value}",
		"battle.subtitle.synergy": "羁绊：{value}",
		"battle.subtitle.buildings": "建筑：{value}",
		"battle.subtitle.prebattle": "战前增益：{value}",
		"battle.title.intro_duel": "{npc} · 初见切磋",
		"battle.subtitle.intro_duel": "第一次拜访前必须先决斗。\n胜利：基础信赖 {win} ｜ 失败：基础信赖 {lose}",
		"dojo.summary.recommended_rank": "推荐据点等级 {value}",
		"dojo.summary.opponents": "对手：{value}",
		"dojo.summary.first_clear": "已首通",
		"dojo.summary.require_previous": "需先通过前一阶",
		"dojo.summary.ticket_missing": "缺少门票材料",
		"dojo.summary.modifiers": "修正：{value}",
		"dojo.tier_1": "试炼一阶",
		"dojo.tier_2": "试炼二阶",
		"dojo.tier_3": "试炼三阶",
	},
	"ja_jp": {
		"menu.title": "霧野遠征",
		"menu.subtitle.runtime": "メイン / 進行中の遠征",
		"menu.subtitle.start": "開始画面 / 新規ゲーム・ロード・設定",
		"menu.continue.season_end": "年間結果を見る",
		"menu.continue.run": "現在の遠征を続ける",
		"menu.start_game": "ゲーム開始",
		"menu.new_run": "新しい遠征",
		"menu.load_save": "セーブ読込",
		"menu.settings": "設定",
		"menu.hint.runtime": "[b]メイン[/b]\n現在の遠征を続けるか、すぐ新しい遠征を始められます。直近の [b]日初セーブ[/b] はロード用に残ります。",
		"menu.hint.start": "[b]開始画面[/b]\nゲーム開始で新しい遠征を作成します。ロードでは直近の [b]日初セーブ[/b] に戻ります。",
		"menu.save.none": "[b]日初セーブ[/b]\n読み込めるランセーブはありません。",
		"menu.save.old": "[b]日初セーブ[/b]\n旧セーブは見つかりましたが、概要情報がありません。",
		"menu.save.latest": "[b]直近の日初セーブ[/b]",
		"menu.summary.position": "現在地：{node}",
		"menu.summary.battle_slots": "前衛枠：{value}",
		"menu.summary.weekly_objective": "週間目標：{value}",
		"menu.summary.unassigned": "未設定",
		"menu.summary.no_objective": "目標記録なし",
		"menu.summary.camp": "キャンプ",
		"settings.summary.title": "[b]現在の設定[/b]",
		"settings.summary.window": "画面モード：{value}",
		"settings.summary.resolution": "ウィンドウ解像度：{value}",
		"settings.summary.motion": "演出強度：{value}",
		"settings.summary.tutorials": "チュートリアル：{value}",
		"settings.summary.language": "言語：{value}",
		"settings.title": "設定",
		"settings.body": "開始画面で画面モード、ウィンドウ解像度、演出、チュートリアル、言語を直接切り替えます。",
		"settings.back": "開始画面へ戻る",
		"settings.window.to_windowed": "ウィンドウに切替",
		"settings.window.to_fullscreen": "全画面に切替",
		"settings.resolution.set": "{value} に設定",
		"settings.motion.to_standard": "標準演出に切替",
		"settings.motion.to_reduced": "簡略演出に切替",
		"settings.tutorials.enable": "チュートリアルを有効化",
		"settings.tutorials.disable": "チュートリアルを無効化",
		"settings.current": "現在：{value}",
		"settings.window.fullscreen": "全画面",
		"settings.window.windowed": "ウィンドウ",
		"settings.motion.standard": "標準",
		"settings.motion.reduced": "簡略",
		"settings.tutorials.on": "有効",
		"settings.tutorials.off": "無効",
		"settings.language.zh_cn": "中国語簡体に切替",
		"settings.language.ja_jp": "日本語に切替",
		"settings.language.en_us": "英語に切替",
		"battle.default_title": "遭遇戦",
		"battle.start": "戦闘開始",
		"battle.end": "戦闘終了",
		"battle.end.win": "勝利",
		"battle.end.lose": "撤退",
		"battle.round": "{round} ラウンド",
		"battle.round_actor": "{round} ラウンド · {actor}",
		"battle.turn.player": "味方ターン",
		"battle.turn.enemy": "敵ターン",
		"battle.roster.allies": "味方ユニット",
		"battle.roster.enemies": "敵ユニット",
		"battle.prompt.player": "{actor} の行動です。先にスキルを選び、その後対象をクリックして確定してください。",
		"battle.prompt.choose_target": "{actor} は {skill} を準備中です。有効な対象をクリックして確定してください。",
		"battle.prompt.choose_enemy_column": "右側の敵ユニット一覧から対象をクリックしてください。",
		"battle.prompt.choose_ally_column": "左側の味方ユニット一覧から対象をクリックしてください。",
		"battle.prompt.enemy_target": "敵対象：{target}",
		"battle.prompt.ally_target": "味方対象：{target}",
		"battle.prompt.none": "未選択",
		"battle.prompt.target": "現在の対象：{target}",
		"battle.prompt.target_none": "現在の対象：未選択",
		"battle.prompt.enemy_thinking": "{actor} が状況を判断中…",
		"battle.prompt.enemy_intent": "{actor} は {target} を狙い、{skill} を使おうとしています。",
		"battle.prompt.action_locked": "{actor} は {target} を狙い、{skill} を放とうとしています。",
		"battle.prompt.capture_locked": "{actor} は {target} の捕獲を狙っています。",
		"battle.capture": "捕獲を試す",
		"battle.capture_hint": "HP が低い野生相手ほど成功しやすい",
		"battle.capture_success_title": "捕獲成功",
		"battle.preview.idle": "行動プレビュー待機",
		"battle.preview.idle_detail": "スキル選択後、行動者・対象・予測結果をここに表示します。",
		"battle.preview.await_actor": "{actor} が待機中",
		"battle.preview.await_detail": "先にスキルを選び、その後対象をクリックしてください。",
		"battle.preview.estimate_damage": "予測ダメージ {min}-{max}",
		"battle.preview.estimate_heal": "予測回復 {value}",
		"battle.preview.guard": "防御態勢を獲得",
		"battle.preview.status_apply": "{status} を付与",
		"battle.preview.enemy_all_damage": "範囲ダメージ {value}",
		"battle.preview.click_target": "ハイライトされた対象をクリックして確定",
		"battle.preview.cancel": "現在のプレビューを取り消す",
		"battle.turn_order.now": "行動中",
		"battle.turn_order.next": "次",
		"battle.turn_order.done": "行動済み",
		"battle.turn_order.ready": "待機",
		"battle.card.acting": "行動中",
		"battle.card.targeted": "ロック中",
		"battle.card.selected": "選択中",
		"battle.card.confirm": "確定可",
		"battle.card.hit": "被弾",
		"battle.card.ko": "KO",
		"battle.marker.active": "[行動]",
		"battle.marker.enemy_target": "[敵対象]",
		"battle.marker.ally_target": "[味方対象]",
		"battle.stat.attack": "攻撃",
		"battle.stat.speed": "速度",
		"battle.stat.hp": "HP",
		"battle.skill.power": "威力 {value}",
		"battle.skill.effect": "効果 {value}",
		"battle.skill.target": "対象 {value}",
		"battle.log.enemy_all": "{actor} は {skill} を放ち、敵全体を圧しました。",
		"battle.log.no_target": "{actor} の {skill} には有効な対象がいません。",
		"battle.log.heal": "{actor} は {target} に {skill} を使い、{value} HP 回復しました。",
		"battle.log.guard": "{actor} は {skill} で防御態勢に入りました。",
		"battle.log.damage": "{actor} は {target} に {skill} を使い、{value} ダメージ。{target} HP {hp}/{max_hp}{suffix}",
		"battle.log.status": "{target} に {status} が付与されました。",
		"battle.log.capture_success": "{actor} は {target} の捕獲に成功しました。",
		"battle.log.capture_fail": "{actor} の捕獲は失敗し、{target} はまだ抵抗しています。",
		"battle.log.round_limit": "{value} ラウンド上限に達したため、残存戦力で判定します。",
		"battle.log.bonus.attack": "共鳴効果：味方攻撃 +{value}。",
		"battle.log.bonus.speed": "共鳴効果：味方速度 +{value}。",
		"battle.log.bonus.hp": "共鳴効果：味方体力 +{value}。",
		"battle.log.bonus.heal": "共鳴効果：回復量 +{value}。",
		"battle.log.bonus.guard": "建築効果：開始時ダメージ軽減 {value}%。",
		"battle.log.bonus.enemy_penalty": "制圧効果：敵攻撃 -{value}。",
		"battle.suffix.super": " · 有利",
		"battle.suffix.resist": " · 不利",
		"battle.subtitle.slots": "前衛枠：{value}",
		"battle.subtitle.synergy": "共鳴：{value}",
		"battle.subtitle.buildings": "建築：{value}",
		"battle.subtitle.prebattle": "戦前効果：{value}",
		"battle.title.intro_duel": "{npc} · 初対面勝負",
		"battle.subtitle.intro_duel": "初回訪問の前に決闘が必要です。\n勝利：基礎信頼 {win} ｜ 敗北：基礎信頼 {lose}",
		"dojo.summary.recommended_rank": "推奨拠点Lv {value}",
		"dojo.summary.opponents": "相手：{value}",
		"dojo.summary.first_clear": "初回突破済み",
		"dojo.summary.require_previous": "前階層の突破が必要",
		"dojo.summary.ticket_missing": "入場素材不足",
		"dojo.summary.modifiers": "補正：{value}",
		"dojo.tier_1": "試練一段",
		"dojo.tier_2": "試練二段",
		"dojo.tier_3": "試練三段",
	},
	"en_us": {
		"menu.title": "Mistwild Expedition",
		"menu.subtitle.runtime": "Main Menu / Expedition in Progress",
		"menu.subtitle.start": "Start Screen / New Game · Load Save · Settings",
		"menu.continue.season_end": "View Year-End Report",
		"menu.continue.run": "Continue Expedition",
		"menu.start_game": "Start Game",
		"menu.new_run": "Start New Expedition",
		"menu.load_save": "Load Save",
		"menu.settings": "Settings",
		"menu.hint.runtime": "[b]Main Menu[/b]\nResume the current expedition or restart immediately. The latest [b]day-start save[/b] remains available for loading.",
		"menu.hint.start": "[b]Start Screen[/b]\nStarting the game creates a new expedition. Loading returns to the latest [b]day-start save[/b].",
		"menu.save.none": "[b]Day-Start Save[/b]\nThere is no run save to load right now.",
		"menu.save.old": "[b]Day-Start Save[/b]\nAn older save was found, but its summary is missing.",
		"menu.save.latest": "[b]Latest Day-Start Save[/b]",
		"menu.summary.position": "Position: {node}",
		"menu.summary.battle_slots": "Battle Slots: {value}",
		"menu.summary.weekly_objective": "Weekly Goal: {value}",
		"menu.summary.unassigned": "Unassigned",
		"menu.summary.no_objective": "No goal recorded",
		"menu.summary.camp": "Camp",
		"settings.summary.title": "[b]Current Settings[/b]",
		"settings.summary.window": "Window Mode: {value}",
		"settings.summary.resolution": "Window Resolution: {value}",
		"settings.summary.motion": "Animation Level: {value}",
		"settings.summary.tutorials": "Tutorials: {value}",
		"settings.summary.language": "Language: {value}",
		"settings.title": "Settings",
		"settings.body": "Adjust window mode, window resolution, animation level, tutorial prompts, and language directly from the start screen.",
		"settings.back": "Back to Start Screen",
		"settings.window.to_windowed": "Switch to Windowed",
		"settings.window.to_fullscreen": "Switch to Fullscreen",
		"settings.resolution.set": "Set to {value}",
		"settings.motion.to_standard": "Use Standard Motion",
		"settings.motion.to_reduced": "Use Reduced Motion",
		"settings.tutorials.enable": "Enable Tutorials",
		"settings.tutorials.disable": "Disable Tutorials",
		"settings.current": "Current: {value}",
		"settings.window.fullscreen": "Fullscreen",
		"settings.window.windowed": "Windowed",
		"settings.motion.standard": "Standard",
		"settings.motion.reduced": "Reduced",
		"settings.tutorials.on": "On",
		"settings.tutorials.off": "Off",
		"settings.language.zh_cn": "Switch to Simplified Chinese",
		"settings.language.ja_jp": "Switch to Japanese",
		"settings.language.en_us": "Switch to English",
		"battle.default_title": "Encounter",
		"battle.start": "Battle Start",
		"battle.end": "Battle End",
		"battle.end.win": "Victory",
		"battle.end.lose": "Retreat",
		"battle.round": "Round {round}",
		"battle.round_actor": "Round {round} · {actor}",
		"battle.turn.player": "Player Turn",
		"battle.turn.enemy": "Enemy Turn",
		"battle.roster.allies": "Allied Units",
		"battle.roster.enemies": "Enemy Units",
		"battle.prompt.player": "{actor} is up. Pick a skill first, then click a target to confirm.",
		"battle.prompt.choose_target": "{actor} is preparing {skill}. Click a valid target to confirm.",
		"battle.prompt.choose_enemy_column": "Click a target in the right enemy unit column.",
		"battle.prompt.choose_ally_column": "Click a target in the left allied unit column.",
		"battle.prompt.enemy_target": "Enemy target: {target}",
		"battle.prompt.ally_target": "Ally target: {target}",
		"battle.prompt.none": "none",
		"battle.prompt.target": "Current target: {target}",
		"battle.prompt.target_none": "Current target: none",
		"battle.prompt.enemy_thinking": "{actor} is reading the field…",
		"battle.prompt.enemy_intent": "{actor} is targeting {target} and preparing {skill}.",
		"battle.prompt.action_locked": "{actor} locks onto {target} and prepares {skill}.",
		"battle.prompt.capture_locked": "{actor} locks onto {target} and prepares a capture attempt.",
		"battle.capture": "Attempt Capture",
		"battle.capture_hint": "Higher success against low-HP wild targets",
		"battle.capture_success_title": "Capture Success",
		"battle.preview.idle": "Waiting for an action preview",
		"battle.preview.idle_detail": "The actor, target, and expected impact will appear here after a skill is selected.",
		"battle.preview.await_actor": "{actor} is ready",
		"battle.preview.await_detail": "Pick a skill, then click a target to confirm.",
		"battle.preview.estimate_damage": "Estimated damage {min}-{max}",
		"battle.preview.estimate_heal": "Estimated heal {value}",
		"battle.preview.guard": "Gain a guard stance",
		"battle.preview.status_apply": "Applies {status}",
		"battle.preview.enemy_all_damage": "AOE damage {value}",
		"battle.preview.click_target": "Click a highlighted target to confirm",
		"battle.preview.cancel": "Cancel current preview",
		"battle.turn_order.now": "Acting",
		"battle.turn_order.next": "Next",
		"battle.turn_order.done": "Done",
		"battle.turn_order.ready": "Ready",
		"battle.card.acting": "Acting",
		"battle.card.targeted": "Targeted",
		"battle.card.selected": "Selected",
		"battle.card.confirm": "Confirm",
		"battle.card.hit": "Hit",
		"battle.card.ko": "KO",
		"battle.marker.active": "[Acting]",
		"battle.marker.enemy_target": "[Enemy Target]",
		"battle.marker.ally_target": "[Ally Target]",
		"battle.stat.attack": "ATK",
		"battle.stat.speed": "SPD",
		"battle.stat.hp": "HP",
		"battle.skill.power": "Power {value}",
		"battle.skill.effect": "Effect {value}",
		"battle.skill.target": "Target {value}",
		"battle.log.enemy_all": "{actor} used {skill} and pressured the whole enemy team.",
		"battle.log.no_target": "{actor}'s {skill} had no valid target.",
		"battle.log.heal": "{actor} used {skill} on {target}, restoring {value} HP.",
		"battle.log.guard": "{actor} entered a guard stance with {skill}.",
		"battle.log.damage": "{actor} hit {target} with {skill} for {value} damage. {target} HP {hp}/{max_hp}{suffix}",
		"battle.log.status": "{target} gained {status}.",
		"battle.log.capture_success": "{actor} successfully captured {target}.",
		"battle.log.capture_fail": "{actor}'s capture failed. {target} is still fighting.",
		"battle.log.round_limit": "Reached the {value}-round limit. Resolving by remaining strength.",
		"battle.log.bonus.attack": "Synergy bonus: ally attack +{value}.",
		"battle.log.bonus.speed": "Synergy bonus: ally speed +{value}.",
		"battle.log.bonus.hp": "Synergy bonus: ally HP +{value}.",
		"battle.log.bonus.heal": "Synergy bonus: healing +{value}.",
		"battle.log.bonus.guard": "Building bonus: opening damage reduction {value}%.",
		"battle.log.bonus.enemy_penalty": "Suppression active: enemy attack -{value}.",
		"battle.suffix.super": " · Strong",
		"battle.suffix.resist": " · Resisted",
		"battle.subtitle.slots": "Battle Slots: {value}",
		"battle.subtitle.synergy": "Synergy: {value}",
		"battle.subtitle.buildings": "Buildings: {value}",
		"battle.subtitle.prebattle": "Pre-Battle Bonus: {value}",
		"battle.title.intro_duel": "{npc} · First Duel",
		"battle.subtitle.intro_duel": "A duel is required before the first visit.\nWin: base trust {win} | Lose: base trust {lose}",
		"dojo.summary.recommended_rank": "Recommended Habitat Lv {value}",
		"dojo.summary.opponents": "Opponents: {value}",
		"dojo.summary.first_clear": "First clear done",
		"dojo.summary.require_previous": "Clear the previous tier first",
		"dojo.summary.ticket_missing": "Missing entry materials",
		"dojo.summary.modifiers": "Modifiers: {value}",
		"dojo.tier_1": "Trial Tier 1",
		"dojo.tier_2": "Trial Tier 2",
		"dojo.tier_3": "Trial Tier 3",
	},
}

func current_language() -> String:
	return _resolve_language("")

func language_name(language_id: String = "") -> String:
	var lang := _resolve_language(language_id)
	return String(LANGUAGE_NAMES.get(lang, LANGUAGE_NAMES[DEFAULT_LANGUAGE]))

func text(key: String, params: Dictionary = {}, language_id: String = "") -> String:
	var lang := _resolve_language(language_id)
	var bundle: Dictionary = TEXT.get(lang, {})
	var fallback: Dictionary = TEXT.get(DEFAULT_LANGUAGE, {})
	var template := String(bundle.get(key, fallback.get(key, key)))
	for param_key in params.keys():
		template = template.replace("{%s}" % String(param_key), str(params[param_key]))
	return template

func type_name(type_id: String, language_id: String = "") -> String:
	var lang := _resolve_language(language_id)
	var bundle: Dictionary = TYPE_NAMES.get(lang, {})
	var fallback: Dictionary = TYPE_NAMES.get(DEFAULT_LANGUAGE, {})
	return String(bundle.get(type_id, fallback.get(type_id, type_id)))

func status_name(status_id: String, language_id: String = "") -> String:
	var lang := _resolve_language(language_id)
	var bundle: Dictionary = STATUS_NAMES.get(lang, {})
	var fallback: Dictionary = STATUS_NAMES.get(DEFAULT_LANGUAGE, {})
	return String(bundle.get(status_id, fallback.get(status_id, status_id)))

func effect_name(effect_id: String, language_id: String = "") -> String:
	var lang := _resolve_language(language_id)
	var bundle: Dictionary = EFFECT_NAMES.get(lang, {})
	var fallback: Dictionary = EFFECT_NAMES.get(DEFAULT_LANGUAGE, {})
	return String(bundle.get(effect_id, fallback.get(effect_id, effect_id)))

func target_name(target_id: String, language_id: String = "") -> String:
	var lang := _resolve_language(language_id)
	var bundle: Dictionary = TARGET_NAMES.get(lang, {})
	var fallback: Dictionary = TARGET_NAMES.get(DEFAULT_LANGUAGE, {})
	return String(bundle.get(target_id, fallback.get(target_id, target_id)))

func skill_name(skill_id: String, fallback_name: String = "", language_id: String = "") -> String:
	var lang := _resolve_language(language_id)
	var bundle: Dictionary = SKILL_NAMES.get(lang, {})
	var fallback: Dictionary = SKILL_NAMES.get(DEFAULT_LANGUAGE, {})
	var translated := String(bundle.get(skill_id, fallback.get(skill_id, "")))
	if not translated.is_empty():
		return translated
	return fallback_name if not fallback_name.is_empty() else skill_id

func _resolve_language(language_id: String) -> String:
	var lang := language_id
	if lang.is_empty():
		lang = String(GameState.settings.get("language", DEFAULT_LANGUAGE))
	if not LANGUAGE_NAMES.has(lang):
		return DEFAULT_LANGUAGE
	return lang
